export const GOSSIP_POSTED = 'GOSSIP_POSTED';
export const GOSSIP_REMOVED = 'GOSSIP_REMOVED';
export const GOSSIP_UPDATED = 'GOSSIP_UPDATED';

export const FETCH_GOSSIPS_REQUEST = 'FETCH_GOSSIPS_REQUEST';
export const FETCH_GOSSIPS_SUCCESS = 'FETCH_GOSSIPS_SUCCESS';

export const SET_CURRENT_GOSSIP = 'SET_CURRENT_GOSSIP';